markdown: kramdown
plugins:
  - jekyll-gist
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from


paginate: 5
paginate_path: blog/:num/

title: agundy
description: Writings of a keyboard operator
url: www.agundy.com
author: Aaron Gunderson
