markdown: kramdown
plugins:
  - jekyll-gist
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from


paginate: 6
paginate_path: blog/:num/

title: agundy
description: Writings of a keyboard operator
author: Aaron Gunderson
