- name: GitHub
  url: http://www.github.com/agundy
  src: /img/github-32px.png

- name: LinkedIn
  url: https://www.linkedin.com/pub/aaron-gunderson/5a/591/252
  src: /img/linkedin-30px.png

- name: Twitter
  url: https://twitter.com/aaron_gundy
  src: /img/twitter-16px.png